name: Docs preview

on:
  pull_request:
    branches:
      - main

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  preview:
    name: Docs preview
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Comment Credentials
        uses: marocchino/sticky-pull-request-comment@v2
        # Only run if PR comes from base repo
        # Reason: forks cannot access secrets and this will always fail
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          GITHUB_TOKEN: ${{ github.token }}
          header: codercom-preview-docs
          message: |
            ✨ code-server docs for PR #${{ github.event.number }} is ready! It will be updated on every commit.
            * _Host_: https://coder.com/docs/code-server/${{ steps.vars.outputs.sha_short }}
            * _Last deploy status_: success
            * _Commit_: ${{ github.event.pull_request.head.sha }}
            * _Workflow status_: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
